BarrCodes/Controllers/BlogController.cs
using BarrCodes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BarrCodes.Controllers
{
    public class BlogController : Controller
    {
        private const int maxPostsPerPage = 10;
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index(int? page)
        {
            var posts = db.BlogPosts.AsEnumerable();
            var pageCount = posts.Count() / maxPostsPerPage;
            var currentPage = page.HasValue ? page.Value : 1;

            posts = posts.OrderByDescending(p => p.DatePosted)
                .Skip((currentPage - 1) * maxPostsPerPage)
                .Take(maxPostsPerPage);

            ViewBag.PageStepperData = new PageStepperData() { CurrentPage = currentPage, PageCount = pageCount };
            return View(posts.ToList());
        }


        public ActionResult Detail(int postID)
        {
            var post = db.BlogPosts
                .Where(p => p.ID == postID)
                .FirstOrDefault();

            ViewBag.Post = post;
            return View();
        }
    }
}

BarrCodes/Views/Shared/PageStepperPartial.cshtml
@{ 
    BarrCodes.Models.PageStepperData stepperData = ViewBag.PageStepperData;
}

@if (stepperData.PageCount > 1)
{
    <div class="btn-group">
        @if (stepperData.CurrentPage > 1)
        {
            @Html.ActionLink("<<", "Index", "Blog", new { page = stepperData.CurrentPage - 1 }, new { @class = "btn btn-default" })
        }

        @if (stepperData.CurrentPage < stepperData.PageCount)
        {
            @Html.ActionLink(">>", "Index", "Blog", new { page = stepperData.CurrentPage + 1 }, new { @class = "btn btn-default" })
        }
    </div>
}

BarrCodes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - BarrCodes</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BarrCodes", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li><a href="http://peculiar-motion.com/wp-content/uploads/2013/01/Resume_MattBarr.pdf">Resume</a></li>
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                @if (User.Identity.IsAuthenticated)

                {
                    @Html.Partial("_LoginPartial")
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    <footer class="footer">
        <div class="container">
            <p>&copy; @DateTime.Now.Year - BarrCodes</p>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>